config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    devise_for :users, controllers: {registrations: 'users/registrations'}
    resources :users do
        resource :profile
    end
    get 'about', to: 'pages#about'
    resources :contacts, only: :create
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :style => { :medium => "300x300", :thumb => "100x100"},
                    :default_url => "/images/:styles/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  has_many :users
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :subscription
  has_one :profile
  
  attr_accessor :stripe_card_token
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: subscription_id, card: stripe_card_token)
      #Set stripe generated customer ID then save to DB
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  #Whitelist custom fields from premium sign up form
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:stripe_card_token, :email, :password, :password_confirmation)}
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    #Instance variable connected to new contact form
    @contact = Contact.new
  end
  
  def create
    #Save contact form with details to @contact {name: 'john', email: 'email@email.com' etc}
    @contact = Contact.new(contact_params)
    if @contact.save
      #Save Contact object to database
      name = params[:contact][:name]
      email = params[:contact][:email]
      comments = params[:contact][:comments]
      #Send params variables to Contact Mailer
      ContactMailer.contact_email(name, email, comments).deliver
      #If all fields are filled in and saved to db then send out message
      flash[:success] = "Message Sent."
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      #Redirect to new action if Contact Object fails to save
      redirect_to new_contact_path
    end
  end
  
  #Security method, strong parameters
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET request for / (homepage)
  def home
    @basic_subscription = Subscription.find(1)
    @pro_subscription = Subscription.find(2)
  end
  
  # Get request for About page
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # Before a user can view profiles verify they are registered and logged in
  before_action :authenticate_user!
  # Allows users to only edit their profile
  before_action :only_current_user
  
  # GET request to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
  # POSTrequest to /users/:user_id/profile after filling out profile form
  def create
    # Retrieve user id and assign it to logged in user
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)
    
    
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path(params[:user_id])
    else
      render action: :new
    end 
  end 
  
  # GET request to /users/:user_id/profile/edit
  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end
  
  #PUT request to /users/:user_id/profile
  def update
    # Retrieve user from DB using ID
    @user = User.find(params[:user_id])
    @profile = @user.profile
    # Mass assign edited profile attributes and update
    if @profile.update_attributes(profile_params)
      flash[:success] = "Updated Profile!"
      #Redirect user to updated profile page
      redirect_to user_path(params[:user_id])
    else
      render action: :edit
      flash[:error] = "Error! Update Unsuccessful"
    end
  end
  
  private
    # Whitelist profile fields from profile form
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :occupation, :telephone_number, :email, :about)
    end 
    
    def only_current_user
      @user = User.find(params[:user_id])
      # If user is trying to access another users profile, redirect them to the homepage
      redirect_to (root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_subscription, only: :new
  #Before saving user to DB check which form they are on and save the parameter
  
  def create
    premium = "prod_IcbXmtGhBK5dph"
    super do |resource|
      if params[:subscription]
        resource.subscription_id = params[:subscription]
        #Product ID generated by stripe
        if resource.subscription_id == premium
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_subscription
      unless (params[:subscription] == '1' || params[:subscription] == '2')
        flash[:notice] = "Please select a subscription plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Security action, lock down controller unless user is logged in
  before_action :authenticate_user!
  
  def index
    @users = User.includes(:profile)
    
  end
  
  # GET request to /user/:id to show user profile
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def occupation_icon
    
    case @user.profile.occupation
    
    when "Developer"
      "<i class='fa fa-code'></i>".html_safe
    when "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    when "Recruiter"
      "<i class='fa fa-search'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class="container">
  <h3 class="text-center">Get In Touch...</h3>
  
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
      <%= form_for @contact do |f| %>
      <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
      </div>
      
      <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
      <%= f.label :comments %>
      <%= f.text_area :comments, class: 'form-control', id: 'text_area' %>
      </div>
      
      <div class="form-group">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>  
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevZone</title>
    <meta name="viewport" content="width-device-width, initial-scale=1.0"
    <%= csrf_meta_tags %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-public-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-comments"></i>
            DevZone
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-bar navbar-right">
            <% if  user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>  
            <%else%>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <%end%>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "My Account", edit_user_registration_path%> </li>
              <li><%= link_to "Community", users_path%> </li>
            <%end%>
            <li><%= link_to "Contact Us", new_contact_path %></li>
            <li><%= link_to "About Us", about_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container alert-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class:"alert alert-#{type}" %>
      <%end%>  
    </div>
    
    <%= csrf_meta_tags %>  
    <%= yield %>
    
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
  <h1>About Page</h1>
  <h4>DevZone focuses on bringing skilled developers, budding entrepenaurs and recruiters together!.</h4>
</div>

app/views/pages/home.html.erb
<div class="parallex">
  <div class="home-page text-center container-fluidwidth">
    <h1>Welcome to DevZone</h1>
    <h3>A membership site where developers and entrepreneur can network</h3>
  </div>
  
  <div class="container home-signup-links">
    <div class="row">
      
      <% if user_signed_in?%>
        <div class="col-md-6 col-md-offset-3">
          <div class="well homepage-well">
            <h2 class="homepage-text text-center">Your Profile</h2>
            <% if current_user.profile %>
              <%= link_to "Edit Profile",  edit_user_profile_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
              <%= link_to "View Profile", user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            <%else%>
              <p class="text-center"> Create your professional profile!</p></p>
              <%= link_to "Create Profile!", new_user_profile_path(current_user.id), class: 'btn btn-default btn-lg btn-block'%>
            <%end%>
          </div>
        </div>
        <div class="col-md-6 col-md-offset-3">
          <div class="well homepage-well">
            <h2 class="homepage-text text-center">The Community</h2>
            <p class="homepage-text text-center"> Visit DevZone Community!</p>
            <%= link_to "Visit Community", users_path, class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
      <%else%>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">Basic Membership</h2>
            <h4>
              <ul>
                <li>Customise your professional profile</li>
                <li>Network with companies worldwide</li>
                <li>Search and view other members profiles</li>
                <br>
              </ul>
            </h4>
            <h2 class="text-center"> FREE!!!</h2>
            <br>
            <%= link_to "Basic Sign Up", new_user_registration_path(subscription: @basic_subscription.id), class: "bt btn-primary btn-lg btn-block text-center" %>
          </div>
        </div>
        
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">Premium Membership</h2>
            <h4>
              <ul>
                <li> See who's viewing your profile </li>
                <li> Access Contact Info </li>
                <li> Access Industry News </li>
                <li> Access Profile Analytics </li>
              </ul>
            </h4>
            <h2 class="text-center"> £9.99/month</h2>
            <br>
            <%= link_to "Premium Sign Up", new_user_registration_path(subscription: @pro_subscription.id), class: "bt btn-primary btn-lg btn-block text-center" %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/profiles/_forms.html.erb
<%= form_for @profile, url: user_profile_path, :html => {:multipart => true} do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :occupation %>
    <%= f.select :occupation, ['Developer', 'Entrepreneur', 'Recruiter'], {}, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :telephone_number %>
    <%= f.text_field :telephone_number, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :about %>
    <%= f.text_area :about, class: 'form-control', id: 'text_area' %>
  </div>
  
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center"> Edit Your Professional Profile! </h1>
      
      <div class="well">
        <%= render 'forms' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1 class="text-center"> Create Your Personalised Profile! </h1>
      <p class="text-center"> Join The Dev Community Today! </p>
      <div class="well">
        <%= render 'forms' %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center"> DevZone Community</h1>
      <ul class="list-unstyled">
        <% @users.each do |user| %>
          <% if user.profile %>
            <li>
              <div class="well row <%= cycle('white-bg', '') %>">
                <div class="col-sm-4 text-center">
                  <% if user.profile.avatar %>
                    <%= link_to user do %>
                      <%= image_tag user.profile.avatar.url, class: 'user-index-avatar' %>
                    <%end%>
                  <%end%>
                </div>
                <div>
                  <%= link_to user do %>
                    <h2><%= user.profile.first_name%> <%= user.profile.last_name%></h2>
                  <%end%>
                  <p>
                    <%= user.profile.occupation%>
                    <% if user.subscription_id == 2%>
                      <span class="label label-danger">Premium</span>
                    <%end%>
                  </p>
                </div>
              </div>
            </li>
          <%end%>
        <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @user.profile.avatar.url, class: 'avatar-img' %>
    </div>
    
    <div class="col-md-6">
      <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
      <h3><span class="occupation-icon"><%= occupation_icon %></span><%= @user.profile.occupation%></h3>
      <div class="well profile-block profile-about">
        <h3>About</h3>
        <p><%= @user.profile.about%></p>
      </div>
      <% if current_user.subscription_id == 2 %>
        <div class="well profile-block contact-info">
          <h3>Contact Info</h3>
          <p>Mobile: <%= @user.profile.telephone_number%></p>
          <p>Email: <%= @user.profile.email%></p>
        </div>
      <%end%>
      
    </div>
  </div>
</div>